#Archivo de configuración de VAS - Valores por defecto
#Puerto en el que se ejecutará el servidor
PORT=8000
#Ruta a la base de datos
DB_PATH=/var/lib/vas/vas.db
#Ruta al archivo de configuración de los equipos
CONFIG_PATH=/var/lib/vas/computers.json
