#!/bin/sh
set -e

echo "[VAS] Ejecutando prerm..."

# Si el servicio existe, detenerlo antes de eliminar archivos
if systemctl list-unit-files | grep -q "^vas.service"; then
    systemctl stop vas.service || true
    systemctl disable vas.service || true
fi

exit 0
